
services:
  - type: web
    name: erp-attendance-api
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.13

      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
